package com.by.generator.dao;

import com.by.generator.bean.SheinSyncData;
import java.util.List;

public interface SheinSyncDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shein_sync_data
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    int insert(SheinSyncData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shein_sync_data
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    List<SheinSyncData> selectAll();
}