package com.by.generator.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shein_sync_data
 */
public class SheinSyncData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.id
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String id;

    /**
     * Database Column Remarks:
     *   希音物料对接码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.materialCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String materialcode;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.supplierMaterialName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String suppliermaterialname;

    /**
     * Database Column Remarks:
     *   仓库名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.warehouseName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String warehousename;

    /**
     * Database Column Remarks:
     *   仓库地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.warehouseAddr
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String warehouseaddr;

    /**
     * Database Column Remarks:
     *   单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.unit
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String unit;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.repertoryNum
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private Integer repertorynum;

    /**
     * Database Column Remarks:
     *   条编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.numberCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String numbercode;

    /**
     * Database Column Remarks:
     *   缸号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.dyelotNumber
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String dyelotnumber;

    /**
     * Database Column Remarks:
     *   门幅cm
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.width
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String width;

    /**
     * Database Column Remarks:
     *   颜色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.materialColorName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String materialcolorname;

    /**
     * Database Column Remarks:
     *   色号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.materialColorCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String materialcolorcode;

    /**
     * Database Column Remarks:
     *   RFID编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shein_sync_data.rfidCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private String rfidcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shein_sync_data
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.id
     *
     * @return the value of shein_sync_data.id
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.id
     *
     * @param id the value for shein_sync_data.id
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.materialCode
     *
     * @return the value of shein_sync_data.materialCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getMaterialcode() {
        return materialcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.materialCode
     *
     * @param materialcode the value for shein_sync_data.materialCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setMaterialcode(String materialcode) {
        this.materialcode = materialcode == null ? null : materialcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.supplierMaterialName
     *
     * @return the value of shein_sync_data.supplierMaterialName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getSuppliermaterialname() {
        return suppliermaterialname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.supplierMaterialName
     *
     * @param suppliermaterialname the value for shein_sync_data.supplierMaterialName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setSuppliermaterialname(String suppliermaterialname) {
        this.suppliermaterialname = suppliermaterialname == null ? null : suppliermaterialname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.warehouseName
     *
     * @return the value of shein_sync_data.warehouseName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getWarehousename() {
        return warehousename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.warehouseName
     *
     * @param warehousename the value for shein_sync_data.warehouseName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setWarehousename(String warehousename) {
        this.warehousename = warehousename == null ? null : warehousename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.warehouseAddr
     *
     * @return the value of shein_sync_data.warehouseAddr
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getWarehouseaddr() {
        return warehouseaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.warehouseAddr
     *
     * @param warehouseaddr the value for shein_sync_data.warehouseAddr
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setWarehouseaddr(String warehouseaddr) {
        this.warehouseaddr = warehouseaddr == null ? null : warehouseaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.unit
     *
     * @return the value of shein_sync_data.unit
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.unit
     *
     * @param unit the value for shein_sync_data.unit
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.repertoryNum
     *
     * @return the value of shein_sync_data.repertoryNum
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public Integer getRepertorynum() {
        return repertorynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.repertoryNum
     *
     * @param repertorynum the value for shein_sync_data.repertoryNum
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setRepertorynum(Integer repertorynum) {
        this.repertorynum = repertorynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.numberCode
     *
     * @return the value of shein_sync_data.numberCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getNumbercode() {
        return numbercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.numberCode
     *
     * @param numbercode the value for shein_sync_data.numberCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setNumbercode(String numbercode) {
        this.numbercode = numbercode == null ? null : numbercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.dyelotNumber
     *
     * @return the value of shein_sync_data.dyelotNumber
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getDyelotnumber() {
        return dyelotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.dyelotNumber
     *
     * @param dyelotnumber the value for shein_sync_data.dyelotNumber
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setDyelotnumber(String dyelotnumber) {
        this.dyelotnumber = dyelotnumber == null ? null : dyelotnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.width
     *
     * @return the value of shein_sync_data.width
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.width
     *
     * @param width the value for shein_sync_data.width
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setWidth(String width) {
        this.width = width == null ? null : width.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.materialColorName
     *
     * @return the value of shein_sync_data.materialColorName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getMaterialcolorname() {
        return materialcolorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.materialColorName
     *
     * @param materialcolorname the value for shein_sync_data.materialColorName
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setMaterialcolorname(String materialcolorname) {
        this.materialcolorname = materialcolorname == null ? null : materialcolorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.materialColorCode
     *
     * @return the value of shein_sync_data.materialColorCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getMaterialcolorcode() {
        return materialcolorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.materialColorCode
     *
     * @param materialcolorcode the value for shein_sync_data.materialColorCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setMaterialcolorcode(String materialcolorcode) {
        this.materialcolorcode = materialcolorcode == null ? null : materialcolorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shein_sync_data.rfidCode
     *
     * @return the value of shein_sync_data.rfidCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public String getRfidcode() {
        return rfidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shein_sync_data.rfidCode
     *
     * @param rfidcode the value for shein_sync_data.rfidCode
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    public void setRfidcode(String rfidcode) {
        this.rfidcode = rfidcode == null ? null : rfidcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shein_sync_data
     *
     * @mbg.generated Wed Jun 28 19:03:24 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", materialcode=").append(materialcode);
        sb.append(", suppliermaterialname=").append(suppliermaterialname);
        sb.append(", warehousename=").append(warehousename);
        sb.append(", warehouseaddr=").append(warehouseaddr);
        sb.append(", unit=").append(unit);
        sb.append(", repertorynum=").append(repertorynum);
        sb.append(", numbercode=").append(numbercode);
        sb.append(", dyelotnumber=").append(dyelotnumber);
        sb.append(", width=").append(width);
        sb.append(", materialcolorname=").append(materialcolorname);
        sb.append(", materialcolorcode=").append(materialcolorcode);
        sb.append(", rfidcode=").append(rfidcode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}